# v3.800.10
name: Release

on:
  workflow_dispatch:

jobs:
  release:
    uses: VirtoCommerce/.github/.github/workflows/release.yml@VCST-2521
    with:
      patchVersion: 'true'
    secrets:
      envPAT: ${{ secrets.REPO_TOKEN }}
