# v3.800.10
name: Release

on:
  workflow_dispatch:
    inputs:
      patchVersion:
        type: boolean
        required: true
        default: false
        description: 'Increment patch version'

jobs:
  release:
    uses: VirtoCommerce/.github/workflow-templates/theme-release-hotfix.yml@VCST-2521
    secrets:
      envPAT: ${{ secrets.REPO_TOKEN }}